spring:
  datasource:
    url: your DB location Url
    username:  username
    password:  password
  jpa:
    hibernate:
      ddl-auto: update

server:
  address: 0.0.0.0
  port: 8080

app:
  tax:
    percentage: 10.0
