spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: Zandaru1
  jpa:
    hibernate:
      ddl-auto: update

server:
  address: 0.0.0.0
  port: 8080

app:
  tax:
    percentage: 10.0
