spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: Zandaru1
  jpa:
    hibernate:
      ddl-auto: update
ticketing:
  total-tickets: 22
  ticket-release-rate: 33
  customer-retrieval-rate: 44
  max-ticket-capacity: 23
