spring:
  datasource:
    url : jdbc:mysql://localhost:3306/test2
    username: root
    password: Zandaru1
  jpa:
    hibernate:
      ddl-auto: update


  security:
    user:
      name: user
      password: "user"
